import vietinbank from '../assets/vietin.svg';
import vietcombank from '../assets/vietcombank.svg';

export interface IBankLists {
  [key: string]: {
    icon: string;
    color: string;
    colorLight: string;
    name: string;
    value: string;
    shortname: string;
  };
}

export const bankLists: IBankLists = {
  acb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Á Châu',
    value: 'acb',
    shortname: 'ACB',
  },
  tpbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Tiên Phong',
    value: 'tpbank',
    shortname: 'TPBank, TPB',
  },
  dab: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Đông Á',
    value: 'dab',
    shortname: 'Đông Á Bank, DAB',
  },
  seabank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Đông Nam Á',
    value: 'seabank',
    shortname: 'SeABank, SSB',
  },
  abbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP An Bình',
    value: 'abbank',
    shortname: 'ABBANK, ABB',
  },
  bacabank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Bắc Á',
    value: 'bacabank',
    shortname: 'BacABank, BAB',
  },
  vietcapitalbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Bản Việt',
    value: 'vietcapitalbank',
    shortname: 'VietCapitalBank, BVB',
  },
  msb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Hàng hải Việt Nam',
    value: 'msb',
    shortname: 'MSB',
  },
  tcb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Kỹ Thương Việt Nam',
    value: 'tcb',
    shortname: 'Techcombank, TCB',
  },
  ksbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Kiên Long',
    value: 'ksbank',
    shortname: 'KSBANK, KLB',
  },
  nab: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Nam Á',
    value: 'nab',
    shortname: 'Nam A Bank, NAB',
  },
  ncb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Quốc Dân',
    value: 'ncb',
    shortname: 'National Citizen Bank, NCB',
  },
  vpbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    value: 'vpbank',
    shortname: 'VPBank, VPB',
  },
  hdbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    value: 'hdbank',
    shortname: 'HDBank, HDB',
  },
  ocb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Phương Đông',
    value: 'ocb',
    shortname: 'Orient Commercial Bank, OCB',
  },
  mb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Quân đội',
    value: 'mb',
    shortname: 'Military Bank, MB',
  },
  pvcombank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Đại chúng Việt Nam',
    value: 'pvcombank',
    shortname: 'PVcombank',
  },
  vib: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    value: 'vib',
    shortname: 'VIBBank, VIB',
  },
  scb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Sài Gòn',
    value: 'scb',
    shortname: 'Sài Gòn, SCB',
  },
  sgb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    value: 'sgb',
    shortname: 'Saigonbank, SGB',
  },
  shb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Sài Gòn – Hà Nội',
    value: 'shb',
    shortname: 'SHBank, SHB',
  },
  vab: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Việt Á',
    value: 'vab',
    shortname: 'VietABank, VAB',
  },
  sacombank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    value: 'sacombank',
    shortname: 'Sacombank, STB',
  },
  bvb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Bảo Việt',
    value: 'bvb',
    shortname: 'BaoVietBank, BVB',
  },
  vietbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    value: 'vietbank',
    shortname: 'VietBank, VBB',
  },
  pgb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Xăng Dầu Petrolimex',
    value: 'pgb',
    shortname: 'Petrolimex Group Bank, PG Bank, PGB',
  },
  eib: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Xuất Nhập khẩu Việt Nam',
    value: 'eib',
    shortname: 'Eximbank, EIB',
  },
  lpb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Bưu điện Liên Việt',
    value: 'lpb',
    shortname: 'LienVietPostBank, LPB',
  },

  vcb: {
    icon: vietinbank,
    color: 'rgb(0,86, 145)',
    colorLight: 'rgba(0, 86, 145, .2)',
    name: 'Ngân Hàng TMCP Ngoại thương Việt Nam',
    value: 'vcb',
    shortname: 'Vietcombank, VCB',
  },

  ctg: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Công Thương Việt Nam',
    value: 'ctg',
    shortname: 'VietinBank, CTG',
  },
  bidv: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân Hàng TMCP Đầu tư và Phát triển Việt Nam',
    value: 'bidv',
    shortname: 'BIDV, BID',
  },
  vbsp: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Chính sách xã hội (Vietnam Bank for Social Policies)',
    value: 'vbsp',
    shortname: 'NHCSXH/VBSP',
  },
  vdb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Phát triển Việt Nam',
    value: 'vdb',
    shortname: 'VDB',
  },
  cb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    value: 'cb',
    shortname: 'CB',
  },
  oceanbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
    value: 'oceanbank',
    shortname: 'Oceanbank',
  },
  gpbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    value: 'gpbank',
    shortname: 'GPBank',
  },
  agribank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    value: 'agribank',
    shortname: 'Agribank',
  },
  shinhanbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    value: 'shinhanbank',
    shortname: 'Shinhan Bank',
  },
  publicbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Public Bank Việt Nam',
    value: 'publicbank',
    shortname: 'Public Bank',
  },
  hsbc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TNHH một thành viên HSBC (Việt Nam)',
    value: 'hsbc',
    shortname: 'HSBC',
  },
  wooribank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Woori Bank tại Việt Nam',
    value: 'wooribank',
    shortname: 'Woori Bank',
  },
  standardchartered: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Standard Chartered',
    value: 'standardchartered',
    shortname: 'Standard Chartered',
  },
  hongleongbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Hong Leong Việt Nam',
    value: 'hongleongbank',
    shortname: 'Hong Leong Bank',
  },
  cimbbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng CIMB Việt Nam',
    value: 'cimbbank',
    shortname: 'CIMB Bank',
  },
  uob: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng UOB tại Việt Nam',
    value: 'uob',
    shortname: 'UOB',
  },
  anz: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TNHH một thành viên ANZ (Việt Nam)',
    value: 'anz',
    shortname: 'ANZ',
  },
  deutdeff: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Deutsche Bank Việt Nam',
    value: 'deutdeff',
    shortname: 'DEUTDEFF',
  },
  citi: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Citibank Việt Nam',
    value: 'citi',
    shortname: 'Citi',
  },
  bidc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Đầu tư và Phát triển Campuchia',
    value: 'bidc',
    shortname: 'BIDC',
  },
  mizuhobank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Mizuho',
    value: 'mizuhobank',
    shortname: 'Mizuhobank',
  },
  ufj: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Tokyo-Mitsubishi UFJ',
    value: 'ufj',
    shortname: 'UFJ',
  },
  smbc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Sumitomo Mitsui Bank',
    value: 'smbc',
    shortname: 'SMBC',
  },
  cba: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Commonwealth Bank tại Việt Nam',
    value: 'cba',
    shortname: 'CBA',
  },
  boc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Bank of China tại Việt Nam',
    value: 'boc',
    shortname: 'BOC',
  },
  maybank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Maybank tại Việt Nam',
    value: 'maybank',
    shortname: 'Maybank',
  },
  icbc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng ICBC tại Việt Nam',
    value: 'icbc',
    shortname: 'ICBC',
  },
  bns: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Scotiabank tại Việt Nam',
    value: 'bns',
    shortname: 'BNS',
  },
  bnp: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng BNP Paribas tại Việt Nam',
    value: 'bnp',
    shortname: 'BNP',
  },
  bkb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Bankok bank tại Việt Nam',
    value: 'bkb',
    shortname: 'BKB',
  },
  worldbank: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Worldbank tại Việt Nam',
    value: 'worldbank',
    shortname: 'Worldbank',
  },
  rhb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng RHB (Malaysia) tại Việt Nam',
    value: 'rhb',
    shortname: 'RHB',
  },
  spa: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Intesa Sanpaolo (Italia) tại Việt Nam',
    value: 'spa',
    shortname: 'Intesa Sanpaolo, SPA',
  },
  jpm: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng JP Morgan Chase Bank (Mỹ) tại Việt Nam',
    value: 'jpm',
    shortname: 'JP Morgan Chase Bank, JPM',
  },
  wfb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Wells Fargo (Mỹ) tại Việt Nam',
    value: 'wfb',
    shortname: 'Wells Fargo, WFB',
  },
  bhf: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng BHF - Bank Aktiengesellschaft (Đức) tại Việt Nam',
    value: 'bhf',
    shortname: 'BHF - Bank Aktiengesellschaft, BHF',
  },
  hvb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Unicredit Bank AG (Đức) tại Việt Nam',
    value: 'hvb',
    shortname: 'Unicredit Bank AG, HVB',
  },
  lbwb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Landesbank Baden-Wuerttemberg (Đức) tại Việt Nam',
    value: 'lbwb',
    shortname: 'Landesbank Baden-Wuerttemberg, LBWB',
  },
  cag: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Commerzbank AG (Đức) tại Việt Nam',
    value: 'cag',
    shortname: 'Commerzbank AG, CAG',
  },
  bs: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Bank Sinopac (Đài Loan) tại Việt Nam',
    value: 'bs',
    shortname: 'Bank Sinopac, BS',
  },
  ccb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Chinatrust Commercial Bank (Đài Loan) tại Việt Nam',
    value: 'ccb',
    shortname: 'Chinatrust Commercial Bank, CCB',
  },
  ubot: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Union Bank of Taiwan (Đài Loan) tại Việt Nam',
    value: 'ubot',
    shortname: 'Union Bank of Taiwan, UBOT',
  },
  hncb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Hua Nan Commercial Bank, Ltd (Đài Loan) tại Việt Nam',
    value: 'hncb',
    shortname: 'Hua Nan Commercial Bank Ltd, HNCB',
  },
  cub: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Cathay United Bank (Đài Loan) tại Việt Nam',
    value: 'cub',
    shortname: 'Cathay United Bank, CUB',
  },
  tib: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Taishin International Bank (Đài Loan) tại Việt Nam',
    value: 'tib',
    shortname: 'Taishin International Bank, TIB',
  },
  lbt: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Land Bank of Taiwan (Đài Loan) tại Việt Nam',
    value: 'lbt',
    shortname: 'Land Bank of Taiwan, LBT',
  },
  sbs: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng The Shanghai Commercial and Savings Bank, Ltd (Đài Loan) tại Việt Nam',
    value: 'sbs',
    shortname: 'The Shanghai Commercial and Savings Bank Ltd, SBS',
  },
  tsk: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Taiwan Shin Kong Commercial Bank (Đài Loan) tại Việt Nam',
    value: 'tsk',
    shortname: 'Taiwan Shin Kong Commercial Bank, TSK',
  },
  sun: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng E.Sun Commercial Bank (Đài Loan) tại Việt Nam',
    value: 'sun',
    shortname: 'E.Sun Commercial Bank, SUN',
  },
  bfce: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Natixis Banque BFCE (Pháp) tại Việt Nam',
    value: 'bfce',
    shortname: 'Natixis Banque BFCE, BFCE',
  },
  sbg: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Société Générale Bank - tại TP. HCM (Pháp) tại Việt Nam',
    value: 'sbg',
    shortname: 'Société Générale Bank, SBG',
  },
  fb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Fortis Bank (Bỉ) tại Việt Nam',
    value: 'fb',
    shortname: 'Fortis Bank, FB',
  },
  rbi: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng RBI (Áo) tại Việt Nam',
    value: 'rbi',
    shortname: 'RBI',
  },
  pb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Phongsavanh (Lào) tại Việt Nam',
    value: 'pb',
    shortname: 'Phongsavanh, PB',
  },
  acom: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Acom Co., Ltd (Nhật) tại Việt Nam',
    value: 'acom',
    shortname: 'ACOM',
  },
  mufj: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Mitsubishi UFJ Lease & Finance Company Limited (Nhật) tại Việt Nam',
    value: 'mufj',
    shortname: 'Mitsubishi UFJ Lease & Finance Company Limited, MUFJ',
  },
  ibk: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Industrial Bank of Korea (Hàn Quốc) tại Việt Nam',
    value: 'ibk',
    shortname: 'Industrial Bank of Korea, IBK',
  },
  keb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Korea Exchange Bank (Hàn Quốc) tại Việt Nam',
    value: 'keb',
    shortname: 'Korea Exchange Bank, KEB',
  },
  kb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Kookmin Bank (Hàn Quốc) tại Việt Nam',
    value: 'kb',
    shortname: 'Kookmin Bank, KB',
  },
  hb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Hana Bank (Hàn Quốc) tại Việt Nam',
    value: 'hb',
    shortname: 'Hana Bank, HB',
  },
  boi: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Bank of India (Ấn Độ) tại Việt Nam',
    value: 'boi',
    shortname: 'Bank of India, BOI',
  },
  iob: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Indian Oversea Bank (Ấn Độ) tại Việt Nam',
    value: 'iob',
    shortname: 'Indian Oversea Bank, IOB',
  },
  rl: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Rothschild Limited (Singapore) tại Việt Nam',
    value: 'rl',
    shortname: 'Rothschild Limited, RL',
  },
  bnk: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Busan - (Hàn Quốc) tại Việt Nam',
    value: 'bnk',
    shortname: 'BNK',
  },
  okb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Ogaki Kyorítu (Nhật Bản) tại Việt Nam',
    value: 'okb',
    shortname: 'Ogaki Kyorítu, OKB',
  },
  kdb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Phát triển Hàn Quốc (Hàn Quốc) tại Việt Nam',
    value: 'kdb',
    shortname: 'KDB',
  },
  adb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Phát triển châu Á (ADB) tại Việt Nam',
    value: 'adb',
    shortname: 'ADB',
  },
  ocbc: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Oversea-Chinese Banking Corp (OCBC) tại Việt Nam',
    value: 'ocbc',
    shortname: 'Oversea-Chinese Banking Corp, OCBC',
  },
  ivb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng TNHH Indovina',
    value: 'ivb',
    shortname: 'Indovina, IVB',
  },
  vrb: {
    icon: vietcombank,
    color: 'rgb(0, 80, 48)',
    colorLight: 'rgba(0, 80, 48, .2)',
    name: 'Ngân hàng Việt - Nga',
    value: 'vrb',
    shortname: 'VRB',
  },
};
